### ISSUE TITLE
snappy and recent GNU/Linux distribution

### ISSUE THREAD

**Issue by adulau** [KDr2/redis-leveldb#14]
For your information,

It would be wise to include snappy in LDFLAGS for all the operating systems:

     LDFLAGS += -lsnappy ../vendor/libleveldb.a -lm -L$(LIBEV)/lib -lev -L$(GMP)/lib -lgmp 

and not only Darwin. As the snappy compression library is required for LevelDB linking.

Thank you very much for your work.

**Comment by KDr2** [comment]
Fixed by 0093566, Thanks.
