### ISSUE TITLE
missing license for the repo

### ISSUE THREAD

**Issue by chenrui333** [KDr2/redis-leveldb#17]
👋 Just found this repo does not have any license, it would be good to add OSI-approved one, https://spdx.org/licenses/

Some popular license choice would be:
- MIT
- Apache-2.0
- BSD-3-Clause

**Comment by yuhanz** [comment]
I have a similar question. What's the license of the project?

**Comment by KDr2** [comment]
It's released under the MIT license. I just added the license file into the project root.
