### ISSUE TITLE
consecutive delete and set

### ISSUE THREAD

**Issue by jsia** [KDr2/redis-leveldb#7]
got this error during a consecutive delete and set 

After a period of time of executing these commands I get a segfault

key = "test"
for (i = 0; i< 100; i++) {
    conn.delete(key)
    conn.set(key, "test")
}

Note: multiple threads

terminate called after throwing an instance of 'std::length_error'
  what():  basic_string::_S_create

Program received signal SIGABRT, Aborted.
[Switching to Thread 801c07400 (LWP 100406/redis-leveldb)]
0x00000008016e0a7c in thr_kill () from /lib/libc.so.7
(gdb) 
(gdb) bt
#0  0x00000008016e0a7c in thr_kill () from /lib/libc.so.7
#1  0x000000080177dd3b in abort () from /lib/libc.so.7
#2  0x0000000800fc4c94 in __gnu_cxx::__verbose_terminate_handler () from /usr/lib/libstdc++.so.6
#3  0x0000000800fc9193 in std::set_unexpected () from /usr/lib/libstdc++.so.6
#4  0x0000000800fc91d3 in std::terminate () from /usr/lib/libstdc++.so.6
#5  0x0000000800fc913a in __cxa_throw () from /usr/lib/libstdc++.so.6
#6  0x000000080101a972 in std::__throw_length_error () from /usr/lib/libstdc++.so.6
#7  0x0000000800fca5d9 in std::string::_Rep::_S_create () from /usr/lib/libstdc++.so.6
#8  0x0000000800fcb305 in std::string::_S_copy_chars () from /usr/lib/libstdc++.so.6
#9  0x0000000800fcb4ba in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string () from /usr/lib/libstdc++.so.6
#10 0x00000000004072fe in RLConnection::do_read ()
#11 0x0000000000407739 in RLConnection::on_readable ()
#12 0x00000008008aac52 in ev_invoke_pending (loop=0x801c6f600) at ev.c:2994
#13 0x00000008008af37c in ev_run (loop=0x801c6f600, flags=Variable "flags" is not available.
) at ev.c:3394
#14 0x00000000004049fb in RLServer::start ()

**Comment by KDr2** [comment]
I am closing this one, because somebody is working on #13.
